name: CI
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install deps
        run: |
          npm ci --no-audit --ignore-scripts

      - name: Build
        run: |
          npm run build

      - name: release
        run: |
          npx semantic-release --extends ./.ci/.releaserc.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: commit updated package.json
        run: |
          if ! git diff --exit-code --quiet package.json ; then
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git config user.name github-actions[bot]
            git add package.json package.json package-lock.json
            git commit -m "chore(release): update release version"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
