name: test

on: ['push']

jobs:
  test:
    runs-on: magcho-runner
    steps:

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: install
      run: |
        npm ci --no-audit --skip-scripts

    - name: test
      run: |
        npm run test
