service: serverless-http-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-offline
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3

package:
  individually: true
  patterns:
    # - '!node_modules/**'
    - "!.DS_Store"
    - "!serverless.*.yml"
    - "!*.md"
    - "!.git/**"
    - "!**/*.sqlite"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  api1:
    handler: functions/api1/handler.get
    package:
      patterns:
        - "./functions/api1/database1.sqlite"
    events:
      - httpApi:
          path: /api1
          method: get

  api2:
    handler: functions/api2/handler.get
    package:
      patterns:
        - "./functions/api2/database2.sqlite"
    events:
      - httpApi:
          path: /api2
          method: get
