name: PostgreSQL service example
on: push

jobs:
  # コンテナジョブのラベル
  postgres:
    # コンテナは Linux ベースのオペレーティングシステムで実行しなければならない
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    # `container-job` が実行される Docker Hub イメージ
    container: node:16

    # `container-job` で実行するサービスコンテナ
    services:
      # サービスコンテナへのアクセスに使用されるラベル
      postgres:
        # Docker Hub のイメージ
        image: postgres
        # postgres のパスワードを入力する
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: pguser
          POSTGRES_DB: db
        # postgres が起動するまで待機するようにヘルスチェックを設定する
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # CI テストを実行する前に、リポジトリにコードのコピーをダウンロードする
      - name: Check out repository code
        uses: actions/checkout@v2

      # `package.json` ファイル内のすべての依存関係のクリーンインストールを実行する
      # 詳しい情報については https://docs.npmjs.com/cli/ci.html を参照
      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL
        # PostgreSQLテーブルを作成し、テーブルにデータを入力してから
        # データを取得するスクリプトを実行する。
        run: node client.js
        # `client.js` スクリプトが新しいPostgreSQLクライアントの作成に使う環境変数。
        env:
          # PostgreSQLサービスコンテナとの通信に使われるホスト名
          POSTGRES_HOST: postgres
          # デフォルトのPostgreSQLポート
          POSTGRES_PORT: 5432


  mysql:
    runs-on: self-hosted
    container: node:16

    services:
      test-database:
        image: mysql/mysql-server:8.0
        env:
          # MYSQL_ROOT_HOST: '%'
          # MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: xxxxxxxxxx
          MYSQL_USER: user
          MYSQL_PASSWORD: xxxxxxxxx
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: |
          npm run test
        env:
          DB_HOST: test-database
          DB_USER: user
          DB_PASSWORD: xxxxxxxxxxx
          DB_DATABASE: xxxxxxxxx
          DB_PORT: 3306
