openapi: 3.0.0
info:
  title: sample
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /hello:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  '':
                    type: string
                required:
                  - message
      operationId: get-hello
components:
  schemas: {}
